#include "chromofold/persistent_page_store.h"
#include <filesystem>
#include <fstream>
#include <map>
#include <memory>
#include <string>
#include <vector>

namespace fs = std::filesystem;
namespace {
constexpr uint64_t MAGIC = 0x3145474150464343ull;
struct RecordHeader { uint64_t magic; uint32_t version; cf_persistent_page_key key; cf_codec_descriptor kc; cf_codec_descriptor vc; uint32_t count; uint64_t kb; uint64_t vb; uint64_t checksum; };
uint64_t key_hash(const cf_persistent_page_key & k){uint64_t h=k.source_hash;h^=uint64_t(k.layer)<<48;h^=uint64_t(k.page_size)<<32;h^=uint64_t(k.kv_head_count)<<16;h^=k.head_dim;return h;}
uint64_t fnv(const uint8_t*p,size_t n){uint64_t h=1469598103934665603ull;for(size_t i=0;i<n;++i){h^=p[i];h*=1099511628211ull;}return h;}
}
struct cf_persistent_store { cf_persistent_store_config config{}; std::string path; std::string model; std::map<uint64_t,uint64_t> index; cf_persistent_store_counters counters{}; std::string error; };
static bool read_record(std::ifstream & in,uint64_t offset,RecordHeader & h,std::vector<uint8_t>&k,std::vector<uint8_t>&v,std::vector<float>&ks,std::vector<float>&vs){in.seekg(offset);if(!in.read((char*)&h,sizeof(h))||h.magic!=MAGIC||h.version!=1)return false;uint64_t ksc=(h.count+h.kc.block_size-1)/h.kc.block_size,vsc=(h.count+h.vc.block_size-1)/h.vc.block_size;k.resize(h.kb);v.resize(h.vb);ks.resize(ksc);vs.resize(vsc);return bool(in.read((char*)k.data(),k.size()).read((char*)v.data(),v.size()).read((char*)ks.data(),ks.size()*sizeof(float)).read((char*)vs.data(),vs.size()*sizeof(float)));}
extern "C" cf_persistent_store * cf_persistent_store_open(const cf_persistent_store_config*c){if(!c||!c->path||!c->model_sha256)return nullptr;auto*s=new cf_persistent_store;s->config=*c;s->path=c->path;s->model=c->model_sha256;if(c->read_enabled&&fs::exists(s->path)){std::ifstream in(s->path,std::ios::binary);uint64_t off=0;while(in){RecordHeader h{};in.seekg(off);if(!in.read((char*)&h,sizeof(h)))break;if(h.magic!=MAGIC||h.version!=1){s->counters.corrupted_records_rejected++;break;}s->index[key_hash(h.key)]=off;uint64_t ksc=(h.count+h.kc.block_size-1)/h.kc.block_size,vsc=(h.count+h.vc.block_size-1)/h.vc.block_size;off+=sizeof(h)+h.kb+h.vb+(ksc+vsc)*sizeof(float);}}return s;}
extern "C" void cf_persistent_store_close(cf_persistent_store*s){delete s;}
extern "C" int cf_persistent_store_put(cf_persistent_store*s,const cf_persistent_page_key*k,const cf_encoded_page*p){if(!s||!k||!p||!s->config.write_enabled)return-1;fs::create_directories(fs::path(s->path).parent_path());std::string tmp=s->path+".tmp";{std::ofstream out(tmp,std::ios::binary|std::ios::app);RecordHeader h{MAGIC,1,*k,p->key_codec,p->value_codec,p->value_count,p->key_payload_bytes,p->value_payload_bytes,p->checksum};uint64_t off=(uint64_t)out.tellp();out.write((char*)&h,sizeof(h));out.write((char*)p->key_payload,p->key_payload_bytes);out.write((char*)p->value_payload,p->value_payload_bytes);uint64_t ksc=(p->value_count+p->key_codec.block_size-1)/p->key_codec.block_size,vsc=(p->value_count+p->value_codec.block_size-1)/p->value_codec.block_size;out.write((char*)p->key_scales,ksc*sizeof(float));out.write((char*)p->value_scales,vsc*sizeof(float));out.flush();if(!out)return-1;s->index[key_hash(*k)]=off;s->counters.records_written++;s->counters.bytes_written+=sizeof(h)+p->key_payload_bytes+p->value_payload_bytes;}fs::rename(tmp,s->path);return 0;}
extern "C" int cf_persistent_store_get(cf_persistent_store*s,const cf_persistent_page_key*k,cf_encoded_page*p){if(!s||!k||!p||!s->config.read_enabled)return-1;auto it=s->index.find(key_hash(*k));if(it==s->index.end()){s->counters.cold_misses++;return-1;}std::ifstream in(s->path,std::ios::binary);RecordHeader h{};std::vector<uint8_t>kb,vb;std::vector<float>ks,vs;if(!read_record(in,it->second,h,kb,vb,ks,vs)){s->counters.corrupted_records_rejected++;return-1;}uint64_t chk=fnv(kb.data(),kb.size())^fnv(vb.data(),vb.size());if(s->config.verify_checksums&&chk!=h.checksum){s->counters.corrupted_records_rejected++;return-1;}p->key_codec=h.kc;p->value_codec=h.vc;p->value_count=h.count;p->key_payload_bytes=h.kb;p->value_payload_bytes=h.vb;p->checksum=h.checksum;p->key_payload=new uint8_t[kb.size()];p->value_payload=new uint8_t[vb.size()];p->key_scales=new float[ks.size()];p->value_scales=new float[vs.size()];std::copy(kb.begin(),kb.end(),p->key_payload);std::copy(vb.begin(),vb.end(),p->value_payload);std::copy(ks.begin(),ks.end(),p->key_scales);std::copy(vs.begin(),vs.end(),p->value_scales);s->counters.records_loaded++;s->counters.warm_hits++;s->counters.bytes_loaded+=kb.size()+vb.size();return 0;}
extern "C" int cf_persistent_store_verify(cf_persistent_store*s){if(!s)return-1;for(auto &e:s->index){std::ifstream in(s->path,std::ios::binary);RecordHeader h{};std::vector<uint8_t>k,v;std::vector<float>ks,vs;if(!read_record(in,e.second,h,k,v,ks,vs))return-1;if(s->config.verify_checksums&&(fnv(k.data(),k.size())^fnv(v.data(),v.size()))!=h.checksum)return-1;}return 0;}
extern "C" int cf_persistent_store_compact(cf_persistent_store*s){return cf_persistent_store_verify(s);}
extern "C" int cf_persistent_store_get_counters(const cf_persistent_store*s,cf_persistent_store_counters*out){if(!s||!out)return-1;*out=s->counters;return 0;}
extern "C" const char * cf_persistent_store_last_error(const cf_persistent_store*s){return s?s->error.c_str():"store is null";}
